"""Add user_id column from Expense model

Revision ID: 62e4826c3d2e
Revises: 73bb7aa9a45d
Create Date: 2024-04-18 15:26:50.464696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e4826c3d2e'
down_revision: Union[str, None] = '73bb7aa9a45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_id', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'user_id')
    # ### end Alembic commands ###
