swagger: '2.0'
info:
  title: Login API
  description: API endpoints for user login
  version: '1.0'
basePath: /api/v1
tags:
  - name: Authentication
    description: Operations related to user authentication
paths:
  /login:
    post:
      tags:
        - Authentication
      summary: Authenticate user
      description: |
        Authenticates a user with the provided credentials and returns an access token.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: credentials
          description: User credentials
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: User's username
              password:
                type: string
                format: password
                description: User's password
      responses:
        '200':
          description: Successful login
          schema:
            type: object
            properties:
              access_token:
                type: string
                description: Access token for the authenticated user
        '400':
          description: Bad request
          schema:
            type: object
            properties:
              message:
                type: string
                description: Error message indicating the cause of the bad request
        '401':
          description: Unauthorized
          schema:
            type: object
            properties:
              message:
                type: string
                description: Error message indicating invalid credentials
